---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: meethour
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: mysql:5.7
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        - containerPort: 3306     
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_DATABASE
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_USERNAME
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PASSWORD
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: SQL_ROOT_PASSWORD
          - name: SQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: SQL_ROOT_PASSWORD
          - name: SQL_CHARSET
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: SQL_CHARSET
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: db-secret
                key:  DB_HOST
      restartPolicy: Always
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: meethour
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - name: adminer
        image: adminer
        ports:
        - containerPort: 8080
        - containerPort: 8080
      restartPolicy: Always      