---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: meethour
spec:
  selector:
    app: db
  ports:
    - name: db-port
      protocol: TCP
      port: 3306  
      targetPort: 3306  

---
apiVersion: v1
kind: Service
metadata:
  name: adminer-service
  namespace: meethour
spec:
  selector:
    app: adminer
  ports:
    - name: adminer-port
      protocol: TCP
      port: 8080    #${ADMINIER_PORT_EXTERNAL}
      targetPort: 8080   #${ADMINIER_PORT_INTERNAL}