apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- db-deploy.yml
- db-service.yml
#configMapGenerator:
#- name: db-configmap
#  envs:
#  - params.properties
secretGenerator:
- name: db-secret
  envs:
  - db-secret.txt