version: '3'

services:
  myapp:
    image: ${PORTAL_IMAGE_VERSION}
    restart: always
    ports:
      - '80:80'
      - '443:443'
    environment:
      # Nginx, PHPs and FPM Environments
      - SSH_KEY= ${SSH_KEY}
      - GIT_REPO= ${GIT_REPO}
      - GIT_EMAIL= ${GIT_EMAIL}
      - GIT_NAME= ${GIT_NAME}
      - GIT_USE_SSH= ${GIT_USE_SSH}
      - GIT_BRANCH= ${GIT_BRANCH}
      - WEBROOT=${WEBROOT}
      - OPcache=${OPcache}
      - ERRORS=${ERRORS}
      - PHP_MEM_LIMIT=${PHP_MEM_LIMIT}
      - PHP_POST_MAX_SIZE=${PHP_POST_MAX_SIZE}
      - PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE}
      - PHP_ERRORS_STDERR=${PHP_ERRORS_STDERR}

      # Application Environment
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT_INTERNAL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}

      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}

      - LOG_CHANNEL=${LOG_CHANNEL}
      - LOG_DEPRECATIONS_CHANNEL=${LOG_DEPRECATIONS_CHANNEL}
      - LOG_LEVEL=${LOG_LEVEL}

      - BROADCAST_DRIVER=${BROADCAST_DRIVER}
      - CACHE_DRIVER=${CACHE_DRIVER}
      - FILESYSTEM_DISK=${FILESYSTEM_DISK}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION}
      - SESSION_DRIVER=${SESSION_DRIVER}
      - SESSION_LIFETIME=${SESSION_LIFETIME}

      - MEMCACHED_HOST=${MEMCACHED_HOST}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PASSWORD}
      
      - MAIL_MAILER=${MAIL_MAILER}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_FROM_NAME="${APP_NAME}"
      
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_USE_PATH_STYLE_ENDPOINT=${AWS_USE_PATH_STYLE_ENDPOINT}

      - PUSHER_APP_ID=${PUSHER_APP_ID}
      - PUSHER_APP_KEY=${PUSHER_APP_KEY}
      - PUSHER_APP_SECRET=${PUSHER_APP_SECRET}
      - PUSHER_HOST=${PUSHER_HOST}
      - PUSHER_PORT=${PUSHER_PORT}
      - PUSHER_SCHEME=${PUSHER_SCHEME}
      - PUSHER_APP_CLUSTER=${PUSHER_APP_CLUSTER}

      - VITE_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
      - VITE_PUSHER_HOST="${PUSHER_HOST}"
      - VITE_PUSHER_PORT="${PUSHER_PORT}"
      - VITE_PUSHER_SCHEME="${PUSHER_SCHEME}"
      - VITE_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
    networks:
      meethour.io:
        aliases:
          - ${DB_HOST}

  # Custom network so all services can communicate using a FQDN
networks:
    meethour.io:
