apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: meethour
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - name: adminer
        image: adminer
        ports:
        - containerPort: 8080
        - containerPort: 8080
      restartPolicy: Always