apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- mysql-master-rc.yml
- mysql-master-service.yml
- mysql-master-hpa.yml
secretGenerator:
- name: mysql-master-secret
  envs:
  - mysql-master-secret.properties