# more mysql-master-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-master-service
  namespace: meethour
  labels:
    app: mysql-master
    # app.kubernetes.io/name: mysql
    # readonly: "true"    
spec:
  type: LoadBalancer
  selector:
    app: mysql-master
  externalTrafficPolicy: Local
  ports:
    - name: http
      protocol: TCP
      port: 3306
      targetPort: 3306
    - name: https
      protocol: TCP
      port: 3307
      targetPort: 3307
