apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-master
  namespace: meethour
  labels:
    name: mysql-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-master
  template:
    metadata:
      labels:
        app: mysql-master
    spec:
      containers:
        - name: mysql-master
          image: prasadvempower/mysql-master:2
          resources:
            requests:
              cpu: 500m
              memory: 200Mi
            limits:
              cpu: 5000m
              memory: 200Mi
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-master-secret
                  key: SQL_ROOT_PASSWORD
            - name: MYSQL_REPLICATION_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-master-secret
                  key: MYSQL_REPLICATION_USER
            - name: MYSQL_REPLICATION_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: mysql-master-secret
                    key: MYSQL_REPLICATION_PASSWORD
            - name: MYSQL_MASTER_SERVICE_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql-master-secret
                  key: DB_MASTER_HOST
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-master-secret
                  key: DB_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-master-secret
                  key: DB_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-master-secret
                  key: DB_PASSWORD
            - name: SQL_CHARSET
              valueFrom:
                secretKeyRef:
                  name: mysql-master-secret
                  key: SQL_CHARSET
      restartPolicy: Always
      # volumes:
      #   - name: mysql-data
      #     hostPath:
      #       path: /var/lib/mysql
      volumes:
        - name: mysql-data
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: mysql-storage
        resources:
          requests:
            storage: 10Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql-data-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi

