GIT_REPO=git@github.com:prasadvempower/breeze.git
GIT_EMAIL=prasad.kumar@v-empower.com
GIT_NAME=prasad.vempower
GIT_USERNAME=prasadvempower
GIT_USE_SSH=1
GIT_BRANCH=main
WEBROOT=/var/www/html/public
OPcache=1
ERRORS=1
SKIP_PHPMIGRATE=0
COMPOSER_ALLOW_SUPERUSER=1
PHP_MEM_LIMIT=512
PHP_POST_MAX_SIZE=1000
PHP_UPLOAD_MAX_FILESIZE=1000
PHP_ERRORS_STDERR=1
APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:2hnPMEWWGE1AYLMIV14rvYqOn3d+GfEoV+9jDM4HokE=
APP_DEBUG=true
APP_URL=localhost
LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug
MAIN_NETWORK_DOMAIN=meethour.io
ADMINIER_PORT_INTERNAL=8080
ADMINIER_PORT_EXTERNAL=8080
BROADCAST_DRIVER=log
CACHE_DRIVER=file
FILESYSTEM_DISK=local
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120
MEMCACHED_HOST=127.0.0.1
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379
MAIL_MAILER=smtp
MAIL_HOST=mailpit
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=hello@example.com
MAIL_FROM_NAME=${APP_NAME}
AWS_ACCESS_KEY_ID= 
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false
PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_HOST=
PUSHER_PORT=443
PUSHER_SCHEME=https
PUSHER_APP_CLUSTER=mt1
VITE_PUSHER_APP_KEY=${PUSHER_APP_KEY}
VITE_PUSHER_HOST=${PUSHER_HOST}
VITE_PUSHER_PORT=${PUSHER_PORT}
VITE_PUSHER_SCHEME=${PUSHER_SCHEME}
VITE_PUSHER_APP_CLUSTER=${PUSHER_APP_CLUSTER}