apiVersion: v1
kind: Service
metadata:
  name: portal-service
  namespace: meethour
  labels:
    app: portal
spec:
  selector:
    app: portal
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
